# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

version: "3.48.0"

includes:
  hook:
    taskfile: ../Taskfile.yaml
    flatten: true
    excludes:
      - predeploy
      - test:unit
    vars:
      hookName: finding-post-processing
      hookSDK: golang
      hookDockerContext: '{{ .TASKFILE_DIR }}/..'
      hookDockerfile: '{{ .TASKFILE_DIR }}/finding-post-processing/hook/Dockerfile'
      additionalHelmInstallArgsForHook: |
        --set="rules[0].matches.anyOf[0].category=Host" \
        --set="rules[0].override.severity=high" \
  test-scan:
    taskfile: ../../scanners/test-scan/Taskfile.yaml

tasks:
  test:unit:
    desc: Run Go unit tests for finding-post-processing
    dir: hook
    cmds:
      - go fmt ./...
      - go vet ./...
      - go test ./...
  predeploy:
    cmds:
      - task: test-scan:build
      - task: test-scan:deploy
