#!/usr/bin/env bash
# SPDX-FileCopyrightText: the secureCodeBox authors
# SPDX-License-Identifier: Apache-2.0

# Script to regenerate sslyze test files using Docker
# This script runs sslyze against various test targets and saves the JSON output

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHART_FILE="${SCRIPT_DIR}/../../Chart.yaml"

# Read sslyze version from Chart.yaml using yq
SSLYZE_VERSION=$(yq eval '.appVersion' "${CHART_FILE}")

echo "Regenerating sslyze test files using version ${SSLYZE_VERSION}..."

# expired.badssl.com
echo "Scanning expired.badssl.com..."
docker run --rm -v "${SCRIPT_DIR}:/output" nablac0d3/sslyze:${SSLYZE_VERSION} \
  --json_out /output/expired.badssl.com.json \
  expired.badssl.com || true

# google.com
echo "Scanning google.com..."
docker run --rm -v "${SCRIPT_DIR}:/output" nablac0d3/sslyze:${SSLYZE_VERSION} \
  --json_out /output/google.com.json \
  google.com || true

# revoked.badssl.com
echo "Scanning revoked.badssl.com..."
docker run --rm -v "${SCRIPT_DIR}:/output" nablac0d3/sslyze:${SSLYZE_VERSION} \
  --json_out /output/revoked.badssl.com.json \
  revoked.badssl.com || true

# self-signed.badssl.com
echo "Scanning self-signed.badssl.com..."
docker run --rm -v "${SCRIPT_DIR}:/output" nablac0d3/sslyze:${SSLYZE_VERSION} \
  --json_out /output/self-signed.badssl.com.json \
  self-signed.badssl.com || true

# tls-v1-0.badssl.com:1010
echo "Scanning tls-v1-0.badssl.com:1010..."
docker run --rm -v "${SCRIPT_DIR}:/output" nablac0d3/sslyze:${SSLYZE_VERSION} \
  --json_out /output/tls-v1-0.badssl.com_1010.json \
  tls-v1-0.badssl.com:1010 || true

# untrusted-root.badssl.com
echo "Scanning untrusted-root.badssl.com..."
docker run --rm -v "${SCRIPT_DIR}:/output" nablac0d3/sslyze:${SSLYZE_VERSION} \
  --json_out /output/untrusted-root.badssl.com.json \
  untrusted-root.badssl.com || true

# wrong.host.badssl.com
echo "Scanning wrong.host.badssl.com..."
docker run --rm -v "${SCRIPT_DIR}:/output" nablac0d3/sslyze:${SSLYZE_VERSION} \
  --json_out /output/wrong.host.badssl.com.json \
  wrong.host.badssl.com || true

# www.securecodebox.io
echo "Scanning www.securecodebox.io..."
docker run --rm -v "${SCRIPT_DIR}:/output" nablac0d3/sslyze:${SSLYZE_VERSION} \
  --json_out /output/www.securecodebox.io.json \
  www.securecodebox.io || true

echo "Done! Test files regenerated."
echo ""
echo "Note: The following test files are special cases and not regenerated by this script:"
echo "  - no-certificate_deployments.json (special test case)"
echo "  - test-empty-report.json (special test case)"
echo "  - unavailable-host.json (special test case)"