[[ADR-0001]]
= ADR-0001: How We do the Combined Network Scans

[cols="h,d",grid=rows,frame=none,stripes=none,caption="Status",%autowidth]
|====

| Status
| ACCEPTED

| Date
| 2020-03-11

| Author(s)
| Daniel Patanin <daniel.patanin@iteratec.com>,
  Sven Strittmatter <sven.strittmatter@iteratec.com>
|====

== Context

We want to use _secureCodeBox_ not only for scans of one particular web project. Instead we want to discover our whole company network and scan every host we find. For that purpose we intended to introduce a "`combined scan`" process model step. The basic idea was:

- Use our _Nmap scanner_ to find all hosts in a network.
- Then feed the list of found hosts into a "`fork process step`"
- This "`fork process step`" starts a complete new sub scan process with
    - _Nmap_ to find all open ports,
    - _Nikto_, _SSLyze_, _ZAP_ etc on the ports,
    - etc.
- Then "`join`" these "`sub scan processes`" together and gather the results.

The best solution to this problem would be to have each scan be able to take the results from any other completed scan and work on them, perhaps with a filter in between. The first idea was to use the sub process step feature built-in in _Camunda_. But this is not possible with the _Camunda_ engine the way we use it for our current processes. Each of our scan processes has it's own BPMN. The results are passed as a "`process global`" variable from step to step inside the process models. A "`sub process`" also would have only this global variable space. This would conflict with the necessity to have a separate variable space for each "`sub scan process`" to not mangle the results for each scanned IP address.

== Decision

We implement these scans as separate process models and combines them in a build pipeline. This means we first scan for IP addresses and store these found hosts in our data backend. Then the build pipeline retrieves the found IP addresses from the data backend and start to scan the hosts each one-by-one with a so called _combined scanner_.

A _combined scanner_ is for example a combination of _Nmap_ and _Nikto_: The _Nmap_ scans for open HTTP ports via service detection and then _Nikto_ scans possibly found HTTP servers.

== Consequences

* To have each combined scan process separately implemented means that we cannot use one scanner for multiple processes. So let's say we want a combined scan including a _Nmap_ scan followed by a _SSH_ scan and another combined scan also starting with a _Nmap_ but followed by a _SSLyze_. We can not use same _Nmap_ scan for both, even if it's identically configured.
* We don't need to invest lot of time into _Camunda_ to examine if it is possible in a clean way to introduce something like scoped variables to Camunda sub processes steps.