[[ADR-0001]]
= ADR-0001: How We do the Combined Network Scans

[cols="h,d",grid=rows,frame=none,stripes=none,caption="Status",%autowidth]
|====

| Status
| ACCEPTED

| Date
| 2020-03-11

| Author(s)
| Daniel Patanin <daniel.patanin@iteratec.com>,
  Sven Strittmatter <sven.strittmatter@iteratec.com>
|====

== Context

We want to use _secureCodeBox_ not only for scans of one particular web project. Instead we want to discover our whole company network and scan every host we find. For that purpose we intended to introduce a "combined scan" process model step. The basic idea was:

- Use our _nmap scanner_ to find all hosts in a network.
- Then feed the list of found hosts into a "fork process step"
- This "fork process step" starts a complete new sub scan process with
    - nmap to find all open ports,
    - Nikto, SSLyze ZAP etz on the ports,
    - etc
- Then "join" these "sub scan processes" together and gather the results

== Decision

The best solution to this problem would be to have each scan be able to take the results from any other completed scan and work on them, perhaps with a filter in between. But this is not possible with the camunda engine the way we use it for our current processes. Each of our scan processes has it's own bpmn. The results are passed as a variable from step to step inside the process models. In order for another scanner to have access to these variables, they need to be stored outside the processes. Furthermore, our scanner need to pass variables through, which indicate wether another scanner needs the results or they should be persisted. We do not have such a storage and variable logic implemented in our engine and camunda models, therefore we're not able to implement a combined scan such as described without reworking our engine and all process models. It is possible though to create processes for specific combined scanner which follow our current architecture.

== Consequences

To have each combined scan process separately implemented means that we cannot use one scanner for multiple processes. So let's say we want a combined scan including a nmap scan followed by a ssh scan and another combined scan also starting with a nmap but followed by a sslyze. We can not use one and the same nmap scan for both, even if it's identically configured. This obviously is a technical flaw from a logical and performance point of view. But this way we don't need to rework our engine and existing process models, which also would add a lot of complexity. But at a curtain point in the future this should be worked on to improve performance and scaling of the combined scan processes.