# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

# Write your dockerfile for the scanner new-scanner here
# Alternatively, you can use an existing image from docker-hub
