#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))

import logging
from zapv2 import ZAPv2

from scbzapv2.zap_configuration import ZapConfiguration
from scbzapv2.zap_context import ZapConfigureContext

#######################################
### BEGINNING OF CONFIGURATION AREA ###
#######################################
## The user only needs to change variable values bellow to make the script
## work according to his/her needs. MANDATORY parameters must not be empty

# MANDATORY. Define the API key generated by ZAP and used to verify actions.
apiKey='eor898q1luuq8054e0e5r9s3jh'

# MANDATORY. Define the listening address of ZAP instance
localProxy = {"http": "http://127.0.0.1:8010", "https": "http://127.0.0.1:8010"}

#################################
### END OF CONFIGURATION AREA ###
#################################

# set up logging to file - see previous section for more details
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(name)-12s %(levelname)-8s: %(message)s',
                    datefmt='%Y-%m-%d %H:%M',
                    filename='zap-extended.log',
                    filemode='w')

logging.info('Configuring ZAP Instance with %s', localProxy)
# Connect ZAP API client to the listening address of ZAP instance
zap = ZAPv2(proxies=localProxy, apikey=apiKey)

testYaml1 = "./tmp/configs/empty-files/"
testYaml2 = "./tmp/configs/empty/"
testYaml3 = "./tmp/configs/scan-overlay/"
testYaml4 = "./tmp/configs/scan-overlay-secrets/"
testYaml5 = "./tmp/configs/bodgeit/"

logging.info("HERE"+ str(sys.path))

config = ZapConfiguration(testYaml3)

logging.debug("ZAP Configuration: %s with type %s", config.get_config(), type(config.get_config()))
logging.debug("ZAP Configuration/Contexts: %s with type %s", config.get_contexts(), type(config.get_contexts()))
logging.debug("ZAP Configuration/Contexts/0: %s with type %s", config.get_context_by_index(0), type(config.get_context_by_index(0)))

# Starting to configure the ZAP Instance based on the given Configuration
local_zap_context = ZapConfigureContext(zap, config)

