#!/usr/bin/make -f

include_guard = set                 # Always include this line (checked in the makefile framework)
scanner = semgrep-scanner           # The name of your scanner

include ../../scanners.mk           # Ensures that all the default makefile targets are included