#!/usr/bin/make -f
#
# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0
#

include_guard = set
scanner = cmseek
custom_scanner = set

include ../../scanners.mk

.PHONY: deploy-test-deps
deploy-test-deps: | deploy-test-dep-old-joomla
