#!/usr/bin/make -f
#
# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0
#

include_guard = set
scanner = wpscan

include ../../scanners.mk

deploy-test-deps: deploy-test-dep-old-wordpress
