/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.securecodebox.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.securecodebox.models.V1ScanSpecAwsElasticBlockStore;
import io.securecodebox.models.V1ScanSpecAzureDisk;
import io.securecodebox.models.V1ScanSpecAzureFile;
import io.securecodebox.models.V1ScanSpecCephfs;
import io.securecodebox.models.V1ScanSpecCinder;
import io.securecodebox.models.V1ScanSpecConfigMap;
import io.securecodebox.models.V1ScanSpecCsi;
import io.securecodebox.models.V1ScanSpecDownwardAPI;
import io.securecodebox.models.V1ScanSpecEmptyDir;
import io.securecodebox.models.V1ScanSpecFc;
import io.securecodebox.models.V1ScanSpecFlexVolume;
import io.securecodebox.models.V1ScanSpecFlocker;
import io.securecodebox.models.V1ScanSpecGcePersistentDisk;
import io.securecodebox.models.V1ScanSpecGitRepo;
import io.securecodebox.models.V1ScanSpecGlusterfs;
import io.securecodebox.models.V1ScanSpecHostPath;
import io.securecodebox.models.V1ScanSpecIscsi;
import io.securecodebox.models.V1ScanSpecNfs;
import io.securecodebox.models.V1ScanSpecPersistentVolumeClaim;
import io.securecodebox.models.V1ScanSpecPhotonPersistentDisk;
import io.securecodebox.models.V1ScanSpecPortworxVolume;
import io.securecodebox.models.V1ScanSpecProjected;
import io.securecodebox.models.V1ScanSpecQuobyte;
import io.securecodebox.models.V1ScanSpecRbd;
import io.securecodebox.models.V1ScanSpecScaleIO;
import io.securecodebox.models.V1ScanSpecSecret;
import io.securecodebox.models.V1ScanSpecStorageos;
import io.securecodebox.models.V1ScanSpecVsphereVolume;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Volume represents a named volume in a pod that may be accessed by any container in the pod.
 */
@ApiModel(description = "Volume represents a named volume in a pod that may be accessed by any container in the pod.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-18T15:41:43.082Z[Etc/UTC]")
public class V1ScanSpecVolumes {
  public static final String SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE = "awsElasticBlockStore";
  @SerializedName(SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE)
  private V1ScanSpecAwsElasticBlockStore awsElasticBlockStore;

  public static final String SERIALIZED_NAME_AZURE_DISK = "azureDisk";
  @SerializedName(SERIALIZED_NAME_AZURE_DISK)
  private V1ScanSpecAzureDisk azureDisk;

  public static final String SERIALIZED_NAME_AZURE_FILE = "azureFile";
  @SerializedName(SERIALIZED_NAME_AZURE_FILE)
  private V1ScanSpecAzureFile azureFile;

  public static final String SERIALIZED_NAME_CEPHFS = "cephfs";
  @SerializedName(SERIALIZED_NAME_CEPHFS)
  private V1ScanSpecCephfs cephfs;

  public static final String SERIALIZED_NAME_CINDER = "cinder";
  @SerializedName(SERIALIZED_NAME_CINDER)
  private V1ScanSpecCinder cinder;

  public static final String SERIALIZED_NAME_CONFIG_MAP = "configMap";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP)
  private V1ScanSpecConfigMap configMap;

  public static final String SERIALIZED_NAME_CSI = "csi";
  @SerializedName(SERIALIZED_NAME_CSI)
  private V1ScanSpecCsi csi;

  public static final String SERIALIZED_NAME_DOWNWARD_A_P_I = "downwardAPI";
  @SerializedName(SERIALIZED_NAME_DOWNWARD_A_P_I)
  private V1ScanSpecDownwardAPI downwardAPI;

  public static final String SERIALIZED_NAME_EMPTY_DIR = "emptyDir";
  @SerializedName(SERIALIZED_NAME_EMPTY_DIR)
  private V1ScanSpecEmptyDir emptyDir;

  public static final String SERIALIZED_NAME_FC = "fc";
  @SerializedName(SERIALIZED_NAME_FC)
  private V1ScanSpecFc fc;

  public static final String SERIALIZED_NAME_FLEX_VOLUME = "flexVolume";
  @SerializedName(SERIALIZED_NAME_FLEX_VOLUME)
  private V1ScanSpecFlexVolume flexVolume;

  public static final String SERIALIZED_NAME_FLOCKER = "flocker";
  @SerializedName(SERIALIZED_NAME_FLOCKER)
  private V1ScanSpecFlocker flocker;

  public static final String SERIALIZED_NAME_GCE_PERSISTENT_DISK = "gcePersistentDisk";
  @SerializedName(SERIALIZED_NAME_GCE_PERSISTENT_DISK)
  private V1ScanSpecGcePersistentDisk gcePersistentDisk;

  public static final String SERIALIZED_NAME_GIT_REPO = "gitRepo";
  @SerializedName(SERIALIZED_NAME_GIT_REPO)
  private V1ScanSpecGitRepo gitRepo;

  public static final String SERIALIZED_NAME_GLUSTERFS = "glusterfs";
  @SerializedName(SERIALIZED_NAME_GLUSTERFS)
  private V1ScanSpecGlusterfs glusterfs;

  public static final String SERIALIZED_NAME_HOST_PATH = "hostPath";
  @SerializedName(SERIALIZED_NAME_HOST_PATH)
  private V1ScanSpecHostPath hostPath;

  public static final String SERIALIZED_NAME_ISCSI = "iscsi";
  @SerializedName(SERIALIZED_NAME_ISCSI)
  private V1ScanSpecIscsi iscsi;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NFS = "nfs";
  @SerializedName(SERIALIZED_NAME_NFS)
  private V1ScanSpecNfs nfs;

  public static final String SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM = "persistentVolumeClaim";
  @SerializedName(SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM)
  private V1ScanSpecPersistentVolumeClaim persistentVolumeClaim;

  public static final String SERIALIZED_NAME_PHOTON_PERSISTENT_DISK = "photonPersistentDisk";
  @SerializedName(SERIALIZED_NAME_PHOTON_PERSISTENT_DISK)
  private V1ScanSpecPhotonPersistentDisk photonPersistentDisk;

  public static final String SERIALIZED_NAME_PORTWORX_VOLUME = "portworxVolume";
  @SerializedName(SERIALIZED_NAME_PORTWORX_VOLUME)
  private V1ScanSpecPortworxVolume portworxVolume;

  public static final String SERIALIZED_NAME_PROJECTED = "projected";
  @SerializedName(SERIALIZED_NAME_PROJECTED)
  private V1ScanSpecProjected projected;

  public static final String SERIALIZED_NAME_QUOBYTE = "quobyte";
  @SerializedName(SERIALIZED_NAME_QUOBYTE)
  private V1ScanSpecQuobyte quobyte;

  public static final String SERIALIZED_NAME_RBD = "rbd";
  @SerializedName(SERIALIZED_NAME_RBD)
  private V1ScanSpecRbd rbd;

  public static final String SERIALIZED_NAME_SCALE_I_O = "scaleIO";
  @SerializedName(SERIALIZED_NAME_SCALE_I_O)
  private V1ScanSpecScaleIO scaleIO;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private V1ScanSpecSecret secret;

  public static final String SERIALIZED_NAME_STORAGEOS = "storageos";
  @SerializedName(SERIALIZED_NAME_STORAGEOS)
  private V1ScanSpecStorageos storageos;

  public static final String SERIALIZED_NAME_VSPHERE_VOLUME = "vsphereVolume";
  @SerializedName(SERIALIZED_NAME_VSPHERE_VOLUME)
  private V1ScanSpecVsphereVolume vsphereVolume;


  public V1ScanSpecVolumes awsElasticBlockStore(V1ScanSpecAwsElasticBlockStore awsElasticBlockStore) {
    
    this.awsElasticBlockStore = awsElasticBlockStore;
    return this;
  }

   /**
   * Get awsElasticBlockStore
   * @return awsElasticBlockStore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecAwsElasticBlockStore getAwsElasticBlockStore() {
    return awsElasticBlockStore;
  }


  public void setAwsElasticBlockStore(V1ScanSpecAwsElasticBlockStore awsElasticBlockStore) {
    this.awsElasticBlockStore = awsElasticBlockStore;
  }


  public V1ScanSpecVolumes azureDisk(V1ScanSpecAzureDisk azureDisk) {
    
    this.azureDisk = azureDisk;
    return this;
  }

   /**
   * Get azureDisk
   * @return azureDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecAzureDisk getAzureDisk() {
    return azureDisk;
  }


  public void setAzureDisk(V1ScanSpecAzureDisk azureDisk) {
    this.azureDisk = azureDisk;
  }


  public V1ScanSpecVolumes azureFile(V1ScanSpecAzureFile azureFile) {
    
    this.azureFile = azureFile;
    return this;
  }

   /**
   * Get azureFile
   * @return azureFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecAzureFile getAzureFile() {
    return azureFile;
  }


  public void setAzureFile(V1ScanSpecAzureFile azureFile) {
    this.azureFile = azureFile;
  }


  public V1ScanSpecVolumes cephfs(V1ScanSpecCephfs cephfs) {
    
    this.cephfs = cephfs;
    return this;
  }

   /**
   * Get cephfs
   * @return cephfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecCephfs getCephfs() {
    return cephfs;
  }


  public void setCephfs(V1ScanSpecCephfs cephfs) {
    this.cephfs = cephfs;
  }


  public V1ScanSpecVolumes cinder(V1ScanSpecCinder cinder) {
    
    this.cinder = cinder;
    return this;
  }

   /**
   * Get cinder
   * @return cinder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecCinder getCinder() {
    return cinder;
  }


  public void setCinder(V1ScanSpecCinder cinder) {
    this.cinder = cinder;
  }


  public V1ScanSpecVolumes configMap(V1ScanSpecConfigMap configMap) {
    
    this.configMap = configMap;
    return this;
  }

   /**
   * Get configMap
   * @return configMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecConfigMap getConfigMap() {
    return configMap;
  }


  public void setConfigMap(V1ScanSpecConfigMap configMap) {
    this.configMap = configMap;
  }


  public V1ScanSpecVolumes csi(V1ScanSpecCsi csi) {
    
    this.csi = csi;
    return this;
  }

   /**
   * Get csi
   * @return csi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecCsi getCsi() {
    return csi;
  }


  public void setCsi(V1ScanSpecCsi csi) {
    this.csi = csi;
  }


  public V1ScanSpecVolumes downwardAPI(V1ScanSpecDownwardAPI downwardAPI) {
    
    this.downwardAPI = downwardAPI;
    return this;
  }

   /**
   * Get downwardAPI
   * @return downwardAPI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecDownwardAPI getDownwardAPI() {
    return downwardAPI;
  }


  public void setDownwardAPI(V1ScanSpecDownwardAPI downwardAPI) {
    this.downwardAPI = downwardAPI;
  }


  public V1ScanSpecVolumes emptyDir(V1ScanSpecEmptyDir emptyDir) {
    
    this.emptyDir = emptyDir;
    return this;
  }

   /**
   * Get emptyDir
   * @return emptyDir
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecEmptyDir getEmptyDir() {
    return emptyDir;
  }


  public void setEmptyDir(V1ScanSpecEmptyDir emptyDir) {
    this.emptyDir = emptyDir;
  }


  public V1ScanSpecVolumes fc(V1ScanSpecFc fc) {
    
    this.fc = fc;
    return this;
  }

   /**
   * Get fc
   * @return fc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecFc getFc() {
    return fc;
  }


  public void setFc(V1ScanSpecFc fc) {
    this.fc = fc;
  }


  public V1ScanSpecVolumes flexVolume(V1ScanSpecFlexVolume flexVolume) {
    
    this.flexVolume = flexVolume;
    return this;
  }

   /**
   * Get flexVolume
   * @return flexVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecFlexVolume getFlexVolume() {
    return flexVolume;
  }


  public void setFlexVolume(V1ScanSpecFlexVolume flexVolume) {
    this.flexVolume = flexVolume;
  }


  public V1ScanSpecVolumes flocker(V1ScanSpecFlocker flocker) {
    
    this.flocker = flocker;
    return this;
  }

   /**
   * Get flocker
   * @return flocker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecFlocker getFlocker() {
    return flocker;
  }


  public void setFlocker(V1ScanSpecFlocker flocker) {
    this.flocker = flocker;
  }


  public V1ScanSpecVolumes gcePersistentDisk(V1ScanSpecGcePersistentDisk gcePersistentDisk) {
    
    this.gcePersistentDisk = gcePersistentDisk;
    return this;
  }

   /**
   * Get gcePersistentDisk
   * @return gcePersistentDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecGcePersistentDisk getGcePersistentDisk() {
    return gcePersistentDisk;
  }


  public void setGcePersistentDisk(V1ScanSpecGcePersistentDisk gcePersistentDisk) {
    this.gcePersistentDisk = gcePersistentDisk;
  }


  public V1ScanSpecVolumes gitRepo(V1ScanSpecGitRepo gitRepo) {
    
    this.gitRepo = gitRepo;
    return this;
  }

   /**
   * Get gitRepo
   * @return gitRepo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecGitRepo getGitRepo() {
    return gitRepo;
  }


  public void setGitRepo(V1ScanSpecGitRepo gitRepo) {
    this.gitRepo = gitRepo;
  }


  public V1ScanSpecVolumes glusterfs(V1ScanSpecGlusterfs glusterfs) {
    
    this.glusterfs = glusterfs;
    return this;
  }

   /**
   * Get glusterfs
   * @return glusterfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecGlusterfs getGlusterfs() {
    return glusterfs;
  }


  public void setGlusterfs(V1ScanSpecGlusterfs glusterfs) {
    this.glusterfs = glusterfs;
  }


  public V1ScanSpecVolumes hostPath(V1ScanSpecHostPath hostPath) {
    
    this.hostPath = hostPath;
    return this;
  }

   /**
   * Get hostPath
   * @return hostPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecHostPath getHostPath() {
    return hostPath;
  }


  public void setHostPath(V1ScanSpecHostPath hostPath) {
    this.hostPath = hostPath;
  }


  public V1ScanSpecVolumes iscsi(V1ScanSpecIscsi iscsi) {
    
    this.iscsi = iscsi;
    return this;
  }

   /**
   * Get iscsi
   * @return iscsi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecIscsi getIscsi() {
    return iscsi;
  }


  public void setIscsi(V1ScanSpecIscsi iscsi) {
    this.iscsi = iscsi;
  }


  public V1ScanSpecVolumes name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Volume&#39;s name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Volume's name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1ScanSpecVolumes nfs(V1ScanSpecNfs nfs) {
    
    this.nfs = nfs;
    return this;
  }

   /**
   * Get nfs
   * @return nfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecNfs getNfs() {
    return nfs;
  }


  public void setNfs(V1ScanSpecNfs nfs) {
    this.nfs = nfs;
  }


  public V1ScanSpecVolumes persistentVolumeClaim(V1ScanSpecPersistentVolumeClaim persistentVolumeClaim) {
    
    this.persistentVolumeClaim = persistentVolumeClaim;
    return this;
  }

   /**
   * Get persistentVolumeClaim
   * @return persistentVolumeClaim
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecPersistentVolumeClaim getPersistentVolumeClaim() {
    return persistentVolumeClaim;
  }


  public void setPersistentVolumeClaim(V1ScanSpecPersistentVolumeClaim persistentVolumeClaim) {
    this.persistentVolumeClaim = persistentVolumeClaim;
  }


  public V1ScanSpecVolumes photonPersistentDisk(V1ScanSpecPhotonPersistentDisk photonPersistentDisk) {
    
    this.photonPersistentDisk = photonPersistentDisk;
    return this;
  }

   /**
   * Get photonPersistentDisk
   * @return photonPersistentDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecPhotonPersistentDisk getPhotonPersistentDisk() {
    return photonPersistentDisk;
  }


  public void setPhotonPersistentDisk(V1ScanSpecPhotonPersistentDisk photonPersistentDisk) {
    this.photonPersistentDisk = photonPersistentDisk;
  }


  public V1ScanSpecVolumes portworxVolume(V1ScanSpecPortworxVolume portworxVolume) {
    
    this.portworxVolume = portworxVolume;
    return this;
  }

   /**
   * Get portworxVolume
   * @return portworxVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecPortworxVolume getPortworxVolume() {
    return portworxVolume;
  }


  public void setPortworxVolume(V1ScanSpecPortworxVolume portworxVolume) {
    this.portworxVolume = portworxVolume;
  }


  public V1ScanSpecVolumes projected(V1ScanSpecProjected projected) {
    
    this.projected = projected;
    return this;
  }

   /**
   * Get projected
   * @return projected
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecProjected getProjected() {
    return projected;
  }


  public void setProjected(V1ScanSpecProjected projected) {
    this.projected = projected;
  }


  public V1ScanSpecVolumes quobyte(V1ScanSpecQuobyte quobyte) {
    
    this.quobyte = quobyte;
    return this;
  }

   /**
   * Get quobyte
   * @return quobyte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecQuobyte getQuobyte() {
    return quobyte;
  }


  public void setQuobyte(V1ScanSpecQuobyte quobyte) {
    this.quobyte = quobyte;
  }


  public V1ScanSpecVolumes rbd(V1ScanSpecRbd rbd) {
    
    this.rbd = rbd;
    return this;
  }

   /**
   * Get rbd
   * @return rbd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecRbd getRbd() {
    return rbd;
  }


  public void setRbd(V1ScanSpecRbd rbd) {
    this.rbd = rbd;
  }


  public V1ScanSpecVolumes scaleIO(V1ScanSpecScaleIO scaleIO) {
    
    this.scaleIO = scaleIO;
    return this;
  }

   /**
   * Get scaleIO
   * @return scaleIO
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecScaleIO getScaleIO() {
    return scaleIO;
  }


  public void setScaleIO(V1ScanSpecScaleIO scaleIO) {
    this.scaleIO = scaleIO;
  }


  public V1ScanSpecVolumes secret(V1ScanSpecSecret secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecSecret getSecret() {
    return secret;
  }


  public void setSecret(V1ScanSpecSecret secret) {
    this.secret = secret;
  }


  public V1ScanSpecVolumes storageos(V1ScanSpecStorageos storageos) {
    
    this.storageos = storageos;
    return this;
  }

   /**
   * Get storageos
   * @return storageos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecStorageos getStorageos() {
    return storageos;
  }


  public void setStorageos(V1ScanSpecStorageos storageos) {
    this.storageos = storageos;
  }


  public V1ScanSpecVolumes vsphereVolume(V1ScanSpecVsphereVolume vsphereVolume) {
    
    this.vsphereVolume = vsphereVolume;
    return this;
  }

   /**
   * Get vsphereVolume
   * @return vsphereVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ScanSpecVsphereVolume getVsphereVolume() {
    return vsphereVolume;
  }


  public void setVsphereVolume(V1ScanSpecVsphereVolume vsphereVolume) {
    this.vsphereVolume = vsphereVolume;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ScanSpecVolumes v1ScanSpecVolumes = (V1ScanSpecVolumes) o;
    return Objects.equals(this.awsElasticBlockStore, v1ScanSpecVolumes.awsElasticBlockStore) &&
        Objects.equals(this.azureDisk, v1ScanSpecVolumes.azureDisk) &&
        Objects.equals(this.azureFile, v1ScanSpecVolumes.azureFile) &&
        Objects.equals(this.cephfs, v1ScanSpecVolumes.cephfs) &&
        Objects.equals(this.cinder, v1ScanSpecVolumes.cinder) &&
        Objects.equals(this.configMap, v1ScanSpecVolumes.configMap) &&
        Objects.equals(this.csi, v1ScanSpecVolumes.csi) &&
        Objects.equals(this.downwardAPI, v1ScanSpecVolumes.downwardAPI) &&
        Objects.equals(this.emptyDir, v1ScanSpecVolumes.emptyDir) &&
        Objects.equals(this.fc, v1ScanSpecVolumes.fc) &&
        Objects.equals(this.flexVolume, v1ScanSpecVolumes.flexVolume) &&
        Objects.equals(this.flocker, v1ScanSpecVolumes.flocker) &&
        Objects.equals(this.gcePersistentDisk, v1ScanSpecVolumes.gcePersistentDisk) &&
        Objects.equals(this.gitRepo, v1ScanSpecVolumes.gitRepo) &&
        Objects.equals(this.glusterfs, v1ScanSpecVolumes.glusterfs) &&
        Objects.equals(this.hostPath, v1ScanSpecVolumes.hostPath) &&
        Objects.equals(this.iscsi, v1ScanSpecVolumes.iscsi) &&
        Objects.equals(this.name, v1ScanSpecVolumes.name) &&
        Objects.equals(this.nfs, v1ScanSpecVolumes.nfs) &&
        Objects.equals(this.persistentVolumeClaim, v1ScanSpecVolumes.persistentVolumeClaim) &&
        Objects.equals(this.photonPersistentDisk, v1ScanSpecVolumes.photonPersistentDisk) &&
        Objects.equals(this.portworxVolume, v1ScanSpecVolumes.portworxVolume) &&
        Objects.equals(this.projected, v1ScanSpecVolumes.projected) &&
        Objects.equals(this.quobyte, v1ScanSpecVolumes.quobyte) &&
        Objects.equals(this.rbd, v1ScanSpecVolumes.rbd) &&
        Objects.equals(this.scaleIO, v1ScanSpecVolumes.scaleIO) &&
        Objects.equals(this.secret, v1ScanSpecVolumes.secret) &&
        Objects.equals(this.storageos, v1ScanSpecVolumes.storageos) &&
        Objects.equals(this.vsphereVolume, v1ScanSpecVolumes.vsphereVolume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(awsElasticBlockStore, azureDisk, azureFile, cephfs, cinder, configMap, csi, downwardAPI, emptyDir, fc, flexVolume, flocker, gcePersistentDisk, gitRepo, glusterfs, hostPath, iscsi, name, nfs, persistentVolumeClaim, photonPersistentDisk, portworxVolume, projected, quobyte, rbd, scaleIO, secret, storageos, vsphereVolume);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ScanSpecVolumes {\n");
    sb.append("    awsElasticBlockStore: ").append(toIndentedString(awsElasticBlockStore)).append("\n");
    sb.append("    azureDisk: ").append(toIndentedString(azureDisk)).append("\n");
    sb.append("    azureFile: ").append(toIndentedString(azureFile)).append("\n");
    sb.append("    cephfs: ").append(toIndentedString(cephfs)).append("\n");
    sb.append("    cinder: ").append(toIndentedString(cinder)).append("\n");
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    csi: ").append(toIndentedString(csi)).append("\n");
    sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
    sb.append("    emptyDir: ").append(toIndentedString(emptyDir)).append("\n");
    sb.append("    fc: ").append(toIndentedString(fc)).append("\n");
    sb.append("    flexVolume: ").append(toIndentedString(flexVolume)).append("\n");
    sb.append("    flocker: ").append(toIndentedString(flocker)).append("\n");
    sb.append("    gcePersistentDisk: ").append(toIndentedString(gcePersistentDisk)).append("\n");
    sb.append("    gitRepo: ").append(toIndentedString(gitRepo)).append("\n");
    sb.append("    glusterfs: ").append(toIndentedString(glusterfs)).append("\n");
    sb.append("    hostPath: ").append(toIndentedString(hostPath)).append("\n");
    sb.append("    iscsi: ").append(toIndentedString(iscsi)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nfs: ").append(toIndentedString(nfs)).append("\n");
    sb.append("    persistentVolumeClaim: ").append(toIndentedString(persistentVolumeClaim)).append("\n");
    sb.append("    photonPersistentDisk: ").append(toIndentedString(photonPersistentDisk)).append("\n");
    sb.append("    portworxVolume: ").append(toIndentedString(portworxVolume)).append("\n");
    sb.append("    projected: ").append(toIndentedString(projected)).append("\n");
    sb.append("    quobyte: ").append(toIndentedString(quobyte)).append("\n");
    sb.append("    rbd: ").append(toIndentedString(rbd)).append("\n");
    sb.append("    scaleIO: ").append(toIndentedString(scaleIO)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    storageos: ").append(toIndentedString(storageos)).append("\n");
    sb.append("    vsphereVolume: ").append(toIndentedString(vsphereVolume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

