# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

{{- if eq (include "operator.garageEnabled" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-garage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: garage
spec:
  type: ClusterIP
  ports:
    - port: 3900
      targetPort: 3900
      protocol: TCP
      name: s3-api
    - port: 3903
      targetPort: 3903
      protocol: TCP
      name: admin
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: garage
{{- end }}
