# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

# Write your dockerfile for the scanner ffuf here
# Alternatively, you can use an existing image from docker-hub
