// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDiscoveryConfig) DeepCopyInto(out *AutoDiscoveryConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ControllerManagerConfigurationSpec.DeepCopyInto(&out.ControllerManagerConfigurationSpec)
	out.Cluster = in.Cluster
	out.ResourceInclusion = in.ResourceInclusion
	in.ServiceAutoDiscoveryConfig.DeepCopyInto(&out.ServiceAutoDiscoveryConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDiscoveryConfig.
func (in *AutoDiscoveryConfig) DeepCopy() *AutoDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(AutoDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoDiscoveryConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfig) DeepCopyInto(out *ClusterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfig.
func (in *ClusterConfig) DeepCopy() *ClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInclusionConfig) DeepCopyInto(out *ResourceInclusionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInclusionConfig.
func (in *ResourceInclusionConfig) DeepCopy() *ResourceInclusionConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceInclusionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanConfig) DeepCopyInto(out *ScanConfig) {
	*out = *in
	out.RepeatInterval = in.RepeatInterval
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanConfig.
func (in *ScanConfig) DeepCopy() *ScanConfig {
	if in == nil {
		return nil
	}
	out := new(ScanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAutoDiscoveryConfig) DeepCopyInto(out *ServiceAutoDiscoveryConfig) {
	*out = *in
	out.PassiveReconcileInterval = in.PassiveReconcileInterval
	in.ScanConfig.DeepCopyInto(&out.ScanConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAutoDiscoveryConfig.
func (in *ServiceAutoDiscoveryConfig) DeepCopy() *ServiceAutoDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAutoDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}
