// SPDX-FileCopyrightText: 2021 iteratec GmbH
//
// SPDX-License-Identifier: Apache-2.0

const fs = require("fs");
const util = require("util");
const {
  validateParser,
} = require("@securecodebox/parser-sdk-nodejs/parser-utils");

// eslint-disable-next-line security/detect-non-literal-fs-filename
const readFile = util.promisify(fs.readFile);

const { parse } = require("./parser");

// test valid xml file
// ad_hc_test.domain.com.xml/html has been generated by running pingcastle against a fresh active directory
// on a Windows Server 2012 R2 VM in VirtualBox
test("should properly parse ping castle xml file", async () => {
  const xmlContent = await readFile(
      __dirname + "/__testFiles__/ad_hc_test.domain.com.xml",
      {
        encoding: "utf8",
      }
  );
  const findings = await parse(xmlContent);
  // validate findings
  await expect(validateParser(findings)).resolves.toBeUndefined();
  expect(findings).toMatchInlineSnapshot(`
Array [
  Object {
    "attributes": Object {
      "riskID": "P-AdminLogin",
    },
    "category": "PrivilegedAccounts",
    "description": "The native administrator account has been used recently: 0 day(s) ago",
    "location": "test.domain.com",
    "name": "AdminControl",
    "osi_layer": "Application",
    "severity": "MEDIUM",
  },
  Object {
    "attributes": Object {
      "riskID": "P-Delegated",
    },
    "category": "PrivilegedAccounts",
    "description": "Presence of Admin accounts which have not the flag \\"this account is sensitive and cannot be delegated\\": 1",
    "location": "test.domain.com",
    "name": "AccountTakeOver",
    "osi_layer": "Application",
    "severity": "MEDIUM",
  },
  Object {
    "attributes": Object {
      "riskID": "A-LAPS-Not-Installed",
    },
    "category": "Anomalies",
    "description": "LAPS doesn't seem to be installed",
    "location": "test.domain.com",
    "name": "PassTheCredential",
    "osi_layer": "Application",
    "severity": "MEDIUM",
  },
  Object {
    "attributes": Object {
      "riskID": "S-SMB-v1",
    },
    "category": "StaleObjects",
    "description": "SMB v1 activated on 1 DC",
    "location": "test.domain.com",
    "name": "OldAuthenticationProtocols",
    "osi_layer": "Application",
    "severity": "LOW",
  },
  Object {
    "attributes": Object {
      "riskID": "P-SchemaAdmin",
    },
    "category": "PrivilegedAccounts",
    "description": "The group Schema Admins is not empty: 1 account(s)",
    "location": "test.domain.com",
    "name": "IrreversibleChange",
    "osi_layer": "Application",
    "severity": "LOW",
  },
  Object {
    "attributes": Object {
      "riskID": "P-RecycleBin",
    },
    "category": "PrivilegedAccounts",
    "description": "The Recycle Bin is not enabled",
    "location": "test.domain.com",
    "name": "IrreversibleChange",
    "osi_layer": "Application",
    "severity": "LOW",
  },
  Object {
    "attributes": Object {
      "riskID": "S-ADRegistration",
    },
    "category": "StaleObjects",
    "description": "Non-admin users can add up to 10 computer(s) to a domain",
    "location": "test.domain.com",
    "name": "Provisioning",
    "osi_layer": "Application",
    "severity": "LOW",
  },
  Object {
    "attributes": Object {
      "riskID": "A-AuditDC",
    },
    "category": "Anomalies",
    "description": "The audit policy on domain controllers does not collect key events.",
    "location": "test.domain.com",
    "name": "Audit",
    "osi_layer": "Application",
    "severity": "LOW",
  },
  Object {
    "attributes": Object {
      "riskID": "A-MinPwdLen",
    },
    "category": "Anomalies",
    "description": "Policy where the password length is less than 8 characters: 1",
    "location": "test.domain.com",
    "name": "WeakPassword",
    "osi_layer": "Application",
    "severity": "LOW",
  },
  Object {
    "attributes": Object {
      "riskID": "A-DC-Spooler",
    },
    "category": "Anomalies",
    "description": "The spooler service is remotely accessible from 1 DC",
    "location": "test.domain.com",
    "name": "PassTheCredential",
    "osi_layer": "Application",
    "severity": "LOW",
  },
  Object {
    "attributes": Object {
      "riskID": "S-DC-SubnetMissing",
    },
    "category": "StaleObjects",
    "description": "The subnet declaration is incomplete [1 IP of DC not found in declared subnets]",
    "location": "test.domain.com",
    "name": "NetworkTopography",
    "osi_layer": "Application",
    "severity": "LOW",
  },
  Object {
    "attributes": Object {
      "riskID": "A-NotEnoughDC",
    },
    "category": "Anomalies",
    "description": "The number of DCs is too small to provide redundancy: 1 DC",
    "location": "test.domain.com",
    "name": "Backup",
    "osi_layer": "Application",
    "severity": "LOW",
  },
  Object {
    "attributes": Object {
      "riskID": "A-NoServicePolicy",
    },
    "category": "Anomalies",
    "description": "No password policy for service account found (MinimumPasswordLength>=20)",
    "location": "test.domain.com",
    "name": "WeakPassword",
    "osi_layer": "Application",
    "severity": "INFORMATIONAL",
  },
  Object {
    "attributes": Object {
      "riskID": "A-NoGPOLLMNR",
    },
    "category": "Anomalies",
    "description": "No GPO has been found which disables LLMNR or at least one GPO does enable it explicitly",
    "location": "test.domain.com",
    "name": "NetworkSniffing",
    "osi_layer": "Application",
    "severity": "INFORMATIONAL",
  },
  Object {
    "attributes": Object {
      "riskID": "A-NoNetSessionHardening",
    },
    "category": "Anomalies",
    "description": "No GPO has been found which implements NetCease",
    "location": "test.domain.com",
    "name": "Reconnaissance",
    "osi_layer": "Application",
    "severity": "INFORMATIONAL",
  },
  Object {
    "attributes": Object {
      "riskID": "A-AuditPowershell",
    },
    "category": "Anomalies",
    "description": "The powershell audit configuration is not fully enabled.",
    "location": "test.domain.com",
    "name": "Audit",
    "osi_layer": "Application",
    "severity": "INFORMATIONAL",
  },
]
`);
});
